"""empty message

Revision ID: 59d7e489d42b
Revises: 11e0484d3fa7
Create Date: 2013-12-28 13:57:06.172066

"""

# revision identifiers, used by Alembic.
revision = '59d7e489d42b'
down_revision = '11e0484d3fa7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
